### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by YifanLi86** [Breakthrough-Energy/SwitchWrapper#16]
- [x] Request more information for each issue @kasparm 
- [x] Adapt existing un-tracked code into a more structured form
- [x] Prepare all inputs data with a single function (#71) @danielolsen 
- [x] Create a launch script to run **Switch** in a reproducible way (#52) @danielolsen
