### ISSUE TITLE
Process output data

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/SwitchWrapper#47]
Below are the steps that we need to follow to use our analysis/plotting ecosystem with results generated by **switc**:
- [x] Read output pickle file (see *BreakthroughEnergySciences/Project/Expansion Planning Optimization Model/Temp Data*)
- [x] Handle timepoints to timestamps conversion (#46)
- [x] Get time series of results (PG, PF, ...) (#50)
  - [x] PF
  - [x] PG
  - [x] duals
  - [x] storage dispatch  
- [x] Build a `Grid` object with information stored in the output file and potentially input data (#49)
- [x] Instantiate `MockScenario` and `MockGrid` objects (#51)
